name: Observe workflow runs

on:
  workflow_run:
    workflows: [Provision tokens]
    types: [requested, completed]

jobs:
  report:
    name: Ghalactic
    uses: ghalactic/repos/.github/workflows/shared-observe-workflow-runs.yml@main
    secrets: inherit
