name: Observe workflow changes

on:
  push:
    paths: [.github/workflows/provision-tokens.yml]
    branches: [main]

jobs:
  report:
    name: Ghalactic
    uses: ghalactic/repos/.github/workflows/shared-observe-workflow-changes.yml@main
    secrets: inherit
